version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

commands:
  set_deploy_key:
    description: Sets the SSH key for project access
    steps:
      - run:
          name: Setup Github as known host
          command: |
            mkdir -p -m 0700 ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - 'a5:1c:81:ad:36:54:22:97:85:4a:47:56:13:53:67:1a'

jobs:
  setup:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: setup workspaces
          command: yarn
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/node_modules
            - ~/lib/node_modules
            - ~/example/node_modules
  lint:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: setup workspaces
          command: yarn
      - run:
          name: run eslint
          command: yarn test:eslint
      - run:
          name: run stylelint
          command: yarn test:stylelint
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: setup workspaces
          command: yarn
      - run:
          name: run unit tests
          command: yarn test:unit --coverage
      - coveralls/upload:
          path_to_lcov: ./lib/coverage/lcov.info
  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: setup workspaces
          command: yarn
      - run:
          name: run build
          command: yarn build:lib
  deploy:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: setup workspaces
          command: yarn
      - run:
          name: build lib
          command: yarn build:lib
      - run:
          name: npm auth
          command: echo $DI_NPM_TOKEN && echo $NPM_TOKEN && echo "//registry.npmjs.org/:_authToken=$DI_NPM_TOKEN" > lib/.npmrc && cat lib/.npmrc
      - set_deploy_key
      - run:
          name: set git user
          command: git config user.email felipe.pereira@loadsmart.com && git config user.name lipe-dev
      - run:
          name: deploy to npm
          command: yarn publish

workflows:
  lint-test-build:
    jobs:
      - setup:
          filters:
            branches:
                ignore: main
      - lint:
          filters:
            branches:
                ignore: main
          requires:
            - setup
      - test:
          filters:
            branches:
                ignore: main
          requires:
            - setup
      - build:
          filters:
            branches:
                ignore: main
          requires:
            - setup
  build-and-deploy:
    jobs:
      - setup:
          filters:
            branches:
              only: main
      - test:
          filters:
            branches:
              only: main
            requires:
              - setup
      - deploy:
          context: loadsmart-ui
          requires:
            - setup
          filters:
            branches:
              only: main

